services:
  # Nome do serviço da nossa API
  api:
    # Instrui o Compose a construir a imagem a partir do Dockerfile
    # no diretório atual ('.')
    build: .
    # Mapeia a porta 8000 do host para a porta 8000 do contêiner
    ports:
      - "8000:8000"
    # Monta volumes para persistência de dados e live-reloading
    volumes:
      # Mapeia o código-fonte local para o diretório /app no contêiner.
      # Qualquer alteração no código local será refletida imediatamente.
      - .:/app
    # Sobrescreve o CMD do Dockerfile para adicionar a flag --reload,
    # ideal para o ambiente de desenvolvimento.
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

